### ISSUE TITLE
Materials Lists

### ISSUE THREAD

**Issue by Sulstice** [materials-data-facility/matchem-eval#2]
Hi, 

I would like to submit this knowledge graph Global-Chem. It's intention is to provide initial training data for select chemical space and allow folk to search through PDFs using common chemical names. For materials, we have some naming for monomers for IUPAC, emerging PFAS systems, and clay adsorption. I'm sure there is more being submitted. 

https://github.com/Global-Chem/global-chem

Think it would be worthwhile?

**Comment by chiang-yuan** [comment]
Hi @Sulstice!

Looks like global chem has been added. I will close this issue :)
